---

- name: Check opatch version in database home
  shell: "{{ oracle_home }}/OPatch/opatch version"
  register: database_opatch_version
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
  changed_when: False
  check_mode: no # always run this command even in check mode

- debug: var=database_opatch_version

- name: Update opatch in database home
  unarchive:
    src: "{{ oracle_stage_install }}/{{ opatch[oracle_version].filename }}"
    dest: "{{ oracle_home }}"
    remote_src: yes
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"
  when: opatch[oracle_version].version not in  database_opatch_version.stdout


